services:
  - type: web
    name: drone-detection-comparison
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: GRADIO_SERVER_NAME
        value: 0.0.0.0
      - key: GRADIO_SERVER_PORT
        value: 7860
